### PR TITLE
Fix Outdated dependencies and vulnerabilities

### LINKED ISSUE #842: Upgrade dependencies with security vulnerabilities
Ideally all `npm outdated` dependencies and at the very least all vulnerable components (`npm audit`) should be upgraded.

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #842

### CODE REVIEW

**Comment by geneh** [comment]
The build has timed out after 60 min, re-running.

**Comment by geneh** [comment]
> @geneh tests are failing but I don't get the same errors locally. Additionally, logs from Netlify are not so understandable, do you have any idea of that?

@storrisi Which Netlify logs?

**Comment by storrisi** [comment]
@geneh I re-ran manually the build this morning too, but it fails for no reason (at least is not explained). Thoughts?

**Comment by geneh** [comment]
Reverting this PR. After the upgrade npm test has stopped working on Ubuntu Azure pipeline and Alpine Linux.
@storrisi I've added npm testlocally in Dockerfile and was able to reproduce the problem:

No tests found related to files changed since last commit.
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |

Reverting your changes yields a normal result.
Can you please fix this problem?

**Pull request merged**
