### PR TITLE
Added new chart for types processed

### LINKED ISSUE #700: add chart to status page to show 'recently processed by type'
see corresponding issue on https://github.com/clearlydefined/service/issues/512

will need a chart added to https://github.com/clearlydefined/website/blob/master/src/components/Navigation/Pages/PageStatus/PageStatus.js (https://clearlydefined.io/status) to show the data

### PR DESCRIPTION
**Pull request by storrisi**
Resolves #700 

Schermata 2019-05-24 alle 15 24 10

Pay attention to don't merge this one before the service related implementation in https://github.com/clearlydefined/service/pull/533 , which is required to work.

### CODE REVIEW

**Comment by dabutvin** [comment]
Awesome! We def need more colors in that color palette lol

I tried adding some more colors and all the ones I chose looked awful

**Comment by storrisi** [comment]
@dabutvin lol you're right, i will add some more colors 👍

**Comment by storrisi** [comment]
I've added a library which generates a color scheme starting from a given color.
It helps to have a set of defined colors, specially if the types list will increase in the future.

**Comment by storrisi** [comment]
As discussed in clearlydefined/service#533  , an update has been made in order to render the chart by tools / types.

We have several data now, so it looks confusing, i'm not 100% sure if this could be very useful:

Schermata 2019-05-30 alle 16 12 54

**Comment by storrisi** [comment]
@geneh would you please take a look on this?

**Comment by geneh** [comment]
> @geneh would you please take a look on this?

It looks good to me. Can you please resolve merging conflicts?

**Comment by storrisi** [comment]
@geneh it should be fine now

**Pull request merged**
