### PR TITLE
updates spdx-license-ids version

### PR DESCRIPTION
**Pull request by nellshamrell**
Signed-off-by: Nell Shamrell <nells@microsoft.com>

### CODE REVIEW

**Comment by MichaelTsengLZ** [comment]
Looks good to me.

**Comment by MichaelTsengLZ** [comment]
Not able to approve.

**Comment by nellshamrell** [comment]
Looks like some of the tests timed out, trying to run them again.

**Comment by nellshamrell** [comment]
@MichaelTsengLZ tests have cleared!

**Review by disulliv — APPROVED** [review]

**Pull request merged**
