### PR TITLE
Fix layout issues on license expressions modal

### LINKED ISSUE #504: Update look of contribute dialog
Looking at the screenshot for the current contribute dialog (below), I suggest some changes...

-  make the dialog narrower
-  move "Type" over to the left and allow the choice to be beside rather than below the "Type" label
- consider putting some data entry parts side by side rather than using a single column

clearlydefined

### PR DESCRIPTION
**Pull request by storrisi**
This one fix a modal style problem mentioned at https://github.com/clearlydefined/website/issues/504#issuecomment-467936328

Fixes #504

### CODE REVIEW

**Comment by storrisi** [comment]
@gianpaj looks like also the SourcePicker modal needs to be fixed:

schermata 2019-02-27 alle 21 10 33

**Comment by gianpaj** [comment]
I've fixed the modal size

**Comment by storrisi** [comment]
@dabutvin could you check why `snyk` is failing for a vulnerability?

**Comment by dabutvin** [comment]
👍

**Pull request merged**
