### PR TITLE
update the look of the definition list

### PR DESCRIPTION
**Pull request by dabutvin**
image

image

### CODE REVIEW

**Comment by storrisi** [comment]
Looks like that some of these fixes have also been addressed in #499 , we should double check the differences.

On which specific issues is related this PR?

**Comment by jeffmcaffer** [comment]
#499 is an issue that mentions some of these changes. So this fixes #499, and perhaps others. Merging this should close #499

**Comment by dabutvin** [comment]
thanks. yeah, some of these ui changes came from just messing around on the fly and weren't fully thought through. I was hoping to address any feedback about the look or feel here in this PR thread.

There are some structure changes here that still need to be reflected in the e2e tests

**Comment by dabutvin** [comment]
actually, looking into this more, the maps are fine the way they are structured. pretty cool.

Any feedback on the way this looks/feels?
[browse](https://deploy-preview-545--clearlydefined.netlify.com/browse)
[fullDetail](https://deploy-preview-545--clearlydefined.netlify.com/definitions/maven/mavencentral/org.flywaydb/flyway-maven-plugin/5.0.7)

**Pull request merged**
