### PR TITLE
Added logo to definitions search field

### LINKED ISSUE #636: Typeahead suggestions should have the logo of the type they are
In the attached screenshot, the Nuget.Client suggestion is for NuGets and the nuget.client suggestion is for GitHub. We should include the logo aside each suggestion so people know which is which.

Screen Shot 2019-03-28 at 3 10 31 PM (2)

### PR DESCRIPTION
**Pull request by storrisi**
This will work in both Homepage and Workspace:

Schermata 2019-04-24 alle 21 39 27
Schermata 2019-04-24 alle 21 39 17

Fixes #636

### CODE REVIEW

**Comment by dabutvin** [comment]
These. Look. Amazing!

**Comment by dabutvin** [comment]
I'm gettting errors trying to select the items in the list - can you take a look?

**Comment by storrisi** [comment]
@dabutvin thanks, i was getting error on e2e tests. Now it should be fine.

**Comment by dabutvin** [comment]
it's working now, but you have to click directly on the text. Can we let users click anywhere on the bar?

**Comment by storrisi** [comment]
@dabutvin i've updated the code, apparently my previous implementation doesn't allow the whole row to be clicked. Thanks!

**Comment by dabutvin** [comment]
this test did eventually pass, but did not report back correctly it seems

**Comment by jeffmcaffer** [comment]
SWEET!

**Pull request merged**
