### PR TITLE
Fix mobile view of Full Details

### LINKED ISSUE #488: Fix mobile view of Full Details
Related to #95

schermata 2019-02-25 alle 11 43 18
schermata 2019-02-25 alle 11 43 36

schermata 2019-02-25 alle 11 43 47

@fossygirl as discussed in #74 i'm not 100% sure that we should show or give to the user the same capabilities of a desktop view in a mobile view.
Is the user supposed to make a contribution in a mobile view, or maybe he could access to a read-only view?

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #488

### CODE REVIEW

**Comment by gianpaj** [comment]
The reason the deployments scripts and tests are failing is that this PR is using the `WindowProvider ` util file what will be merged in https://github.com/clearlydefined/website/pull/484

**Comment by storrisi** [comment]
This one needs #484 to be merged.
If that one would be approved we can hopefully fix also the problems addressed here and have the solution in place soon.

**Comment by storrisi** [comment]
Once #484 will be merged, we'll be able to complete the work here.

**Comment by gianpaj** [comment]
I've pushed some changes to improve the Full Details in modal and page modes:

**Comment by storrisi** [comment]
@dabutvin this PR has been completed weeks ago, are there some specific reasons to not merge this one? I'm happy to apply any required change if needed.

**Comment by dabutvin** [comment]
no, it just slipped through the cracks.

We should integrate this one. Can you resolve the conflicts?

**Comment by storrisi** [comment]
@dabutvin done

**Pull request merged**
