### PR TITLE
Add matchingFalse param for definitions request

### LINKED ISSUE #823: Add a matchCasing=false parameter when calling the /definitions endpoint
As explained on https://github.com/clearlydefined/service/issues/589#issuecomment-529936105 and because of what we found as #604 , we need the Website to keep using a non-post-processed response.
Please add a query string parameter ```matchCasing=false```, on requests to the /definitions endpoint which end up composing curations. Alternatively, just replace on all usages of that endpoint.

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #823

### CODE REVIEW

**Comment by geneh** [comment]
Should E2E or other tests be updated? Let's deploy both the website and the service changes together and test to make sure nothing gets broken.

**Comment by storrisi** [comment]
@geneh E2E and tests don't use real endpoints, they just mock the response.

**Comment by geneh** [comment]
Okay. I've been playing with Netlify deployment https://deploy-preview-824--clearlydefined.netlify.com and definitions endpoints do not seem to have the new parameter. It was deployed more than three hours ago, so it shouldn't be a caching issue.
@storrisi Can you point me to a page where the new parameter is expected to show up?

**Comment by storrisi** [comment]
@geneh you were right, thanks to your tests I discovered that the matchCasing param should be passed as a string.
Since its value was a boolean false, it was never added to the query string.

**Comment by geneh** [comment]
Great, thanks!

**Pull request merged**
