### PR TITLE
Issue #482 - Add guidance on popup for curation submission

### LINKED ISSUE #482: Add guidance on popup for curation submission
Since we changed the generation of the PR title to be the title the user enters on their curation submission popup, we should tell them in the help text that "this text will be used to generate the title of the PR." Might make them slightly more likely to enter something meaningful. :-)

@dabutvin for visibility

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #482

### CODE REVIEW

**Comment by gianpaj** [comment]
For quicker review here is the text in Summary field in the curation Popup Modal:
clearlydefined

**Comment by jeffmcaffer** [comment]
Perhaps we should just change the UI to "Title" if it actually is going to be the title.

Then the placeholder can be something like "Short (100 char) description. Used as PR title"

**Comment by gianpaj** [comment]
Sounds good. I've made those changes

**Comment by gianpaj** [comment]
I've made the style changes as per #504.

@jeffmcaffer I've left the Type selector on the top right as it was originally suppose to look. There was missing CSS class.

Is this ok?
clearlydefined

**Comment by dabutvin** [comment]
👍

**Pull request merged**
