### PR TITLE
Issue #487 - Fix mobile view of About Page

### LINKED ISSUE #487: Fix mobile view of About Page
schermata 2019-02-25 alle 11 37 17
Related to #95

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #487

### CODE REVIEW

**Comment by dabutvin** [comment]
the desktop view of the partners should stay in a grid

image

should be 
image

**Comment by dabutvin** [comment]
Can we reduce the vertical space above 'About ClearlyDefined' ?
image

**Comment by gianpaj** [comment]
Hi @dabutvin , I've pushed a fix for both issues.

There was a merge somewhere that removed a change made to the `.center-block` class.

FYI: the test's failure are not related to this PR and are fixed in #523

**Comment by dabutvin** [comment]
👍

**Pull request merged**
