### PR TITLE
Fix npm outdated dependencies

### LINKED ISSUE #842: Upgrade dependencies with security vulnerabilities
Ideally all `npm outdated` dependencies and at the very least all vulnerable components (`npm audit`) should be upgraded.

### PR DESCRIPTION
**Pull request by storrisi**
Fixes #842

### CODE REVIEW

**Comment by geneh** [comment]
There are no updates to the dependencies here. Can they be added?

**Comment by storrisi** [comment]
It looks that the reverted changes removed my upgrades. Let me investigate.

**Comment by geneh** [comment]
@storrisi Any update on this?

**Comment by storrisi** [comment]
I'm still getting errors while trying to run `npm audit fix` . Just trying to figure out why

**Comment by geneh** [comment]
Which package is causing it?

**Comment by storrisi** [comment]
The log doesn't explain which is, I'm trying to remove and adding back dependencies to see which is the one that fails

**Comment by storrisi** [comment]
@geneh i think i found the lib that cause the problem. Apparently is `@clearlydefined/spdx`

**Comment by storrisi** [comment]
Ok, after a lot of tries, i can confirm that the problem is on `@clearlydefined/spdx` lib.
As soon this lib is added to the project, the `npm audit` command starts failing.
Maybe it has some deps to be updated as well?

**Comment by geneh** [comment]
Good catch. Yes, it's possible. Luckily, we own this repository. Could you please check?

**Comment by storrisi** [comment]
@geneh sure i will

**Comment by geneh** [comment]
Is the code ready to be merged?

**Comment by storrisi** [comment]
Yes it is!

**Comment by geneh** [comment]
Great, thanks!

**Pull request merged**
